services:
  - type: web
    name: ict-ticketing-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: daphne ict_ticketing.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ict_ticketing.settings
      - key: SECRET_KEY
        value: your-generated-secret-key
      - key: REDIS_URL
        fromService:
          name: redis
          type: redis
    autoDeploy: true

databases:
  - name: redis
    ipAllowList: []
