services:
  - type: web
    name: ticketing-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: daphne ict_ticketing.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ict_ticketing.settings
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DATABASE_URL
        value: (Render will auto-generate this if using PostgreSQL)
