# Generated by Django 4.2.7 on 2025-07-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_rename_matric_number_studentrecord_id_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentrecord',
            old_name='programme',
            new_name='department',
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='office',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
