# Generated by Django 4.2.7 on 2025-07-31 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_rename_programme_studentrecord_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentRecord',
        ),
    ]
